CREATE TABLE [dbo].[EMPLOYEE]
(
	[EMP_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
	[USER_ROLE] INT NULL, 
    [ORGN_ID] INT NULL, 
    [FIRST_NAME] VARCHAR(50) NULL, 
    [LAST_NAME] VARCHAR(50) NULL, 
    [CONTACT] NCHAR(10) NULL, 
    [USER_NAME] VARCHAR(50) NULL, 
    [PASSWORD] VARCHAR(50) NULL, 
    [STATUS] INT NULL, 
    CONSTRAINT [FK_EMPLOYEE_ROLE] FOREIGN KEY ([USER_ROLE]) REFERENCES [dbo].[USER_ROLE], 
    CONSTRAINT [FK_EMPLOYEE_ORGN] FOREIGN KEY ([ORGN_ID]) REFERENCES [dbo].[ORGANIZATION], 
    CONSTRAINT [FK_EMPLOYEE_STATUS] FOREIGN KEY ([STATUS]) REFERENCES [dbo].[STATUS]
)
