CREATE TABLE [dbo].[ENTITY_WORK]
(
	[EW_WORK] INT NOT NULL PRIMARY KEY IDENTITY, 
    [WF_ID] INT NULL, 
    [ENTITY_NAME] VARCHAR(50) NULL, 
    [REMARK] VARCHAR(50) NULL, 
    [ASSIGN_DATE] DATE NULL, 
    [END_DATE] DATE NULL, 
    [STATUS] INT NULL, 
    CONSTRAINT [FK_ENTITY_WORK_WF] FOREIGN KEY ([WF_ID]) REFERENCES [dbo].[WORK_FLOW], 
    CONSTRAINT [FK_ENTITY_WORK_STATUS] FOREIGN KEY ([STATUS]) REFERENCES [dbo].[STATUS]
)
