CREATE TABLE [dbo].[ENTITY_EMPLOYEE]
(
	[EE_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ENTITY_ID] INT NULL, 
    [EMP_ID] INT NULL, 
    [STATUS] INT NULL, 
    [REMARK] NCHAR(10) NULL, 
    CONSTRAINT [FK_ENTITY_EMPLOYEE_ENTITY] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ENTITY_WORK], 
    CONSTRAINT [FK_ENTITY_EMPLOYEE_EMP] FOREIGN KEY ([EMP_ID]) REFERENCES [dbo].[EMPLOYEE], 
    CONSTRAINT [FK_ENTITY_EMPLOYEE_STATUS] FOREIGN KEY ([STATUS]) REFERENCES [dbo].[STATUS]
)
