CREATE TABLE [dbo].[ORGANIZATION]
(
	[ORG_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ORGANIZATION] VARCHAR(50) NULL, 
    [ADR1] VARCHAR(50) NULL, 
    [ADR2] VARCHAR(50) NULL, 
    [CITY] VARCHAR(50) NULL, 
    [CONTATC] NCHAR(10) NULL
)
