CREATE TABLE [dbo].[WORKFLOW_MANAGER]
(
	[WB_ID] INT NOT NULL  IDENTITY, 
    [WORK_FLOW] INT NULL, 
    [MANAGER] INT NOT NULL, 
    [STATUS] INT NULL, 
    [REMARK] VARCHAR(50) NULL, 
    CONSTRAINT [FK_WORKFLOW_MANAGER_WF] FOREIGN KEY ([WORK_FLOW]) REFERENCES [dbo].[WORK_FLOW], 
    PRIMARY KEY ([WB_ID]), 
    CONSTRAINT [FK_WORKFLOW_MANAGER_MANAGER] FOREIGN KEY ([MANAGER]) REFERENCES [dbo].[EMPLOYEE], 
    CONSTRAINT [FK_WORKFLOW_MANAGER_STATUS] FOREIGN KEY ([STATUS]) REFERENCES [dbo].[STATUS]
)
