CREATE TABLE [dbo].[WORK_FLOW]
(
	[WF_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [WF_NAME] VARCHAR(50) NULL, 
	[STATUS] INT NULL,
    [CREATE_DATE] DATE NULL, 
    [END_DATE] DATE NULL, 
    CONSTRAINT [FK_WORK_FLOW_STATUS] FOREIGN KEY ([STATUS]) REFERENCES [dbo].[STATUS] 
)
