//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOFT_WORK_FLOW_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ENTITY_EMPLOYEE = new HashSet<ENTITY_EMPLOYEE>();
            this.WORKFLOW_MANAGER = new HashSet<WORKFLOW_MANAGER>();
        }
    
        public int EMP_ID { get; set; }
        public Nullable<int> USER_ROLE { get; set; }
        public Nullable<int> ORGN_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CONTACT { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        public virtual USER_ROLE USER_ROLE1 { get; set; }
        public virtual STATUS STATUS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_EMPLOYEE> ENTITY_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW_MANAGER> WORKFLOW_MANAGER { get; set; }
    }
}
