//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOFT_WORK_FLOW_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITY_EMPLOYEE
    {
        public int EE_ID { get; set; }
        public Nullable<int> ENTITY_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string REMARK { get; set; }
    
        public virtual ENTITY_WORK ENTITY_WORK { get; set; }
        public virtual STATUS STATUS1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
