//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOFT_WORK_FLOW_MANAGEMENT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WORK_FLOWEntities : DbContext
    {
        public WORK_FLOWEntities()
            : base("name=WORK_FLOWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ENTITY_EMPLOYEE> ENTITY_EMPLOYEE { get; set; }
        public virtual DbSet<ENTITY_WORK> ENTITY_WORK { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<WORK_FLOW> WORK_FLOW { get; set; }
        public virtual DbSet<WORKFLOW_MANAGER> WORKFLOW_MANAGER { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
    }
}
